
export enum SpellName {
  LUMOS = 'lumos',
  EXPELLIARMUS = 'expelliarmus',
  RICTUSEMPRA = 'rictusempra',
  WINGARDIUM_LEVIOSA = 'wingardium leviosa',
  ALOHOMORA = 'alohomora',
  FLIPENDO = 'flipendo',
  NOX = 'nox',
  HOMORPHUS = 'homorphus',
  CHARM_REVERSAL = 'charmReversal',
  MELOFORS = 'melofors',

  ENGORGIO = 'engorgio',
  INCENDIO = 'incendio',
  EPISKEY = 'episkey',
  REDUCTO = 'reducto',

  FINITE = 'finite',
  PETRIFICUS = 'petrificus',
  DEPULSO = 'depulso',
  RIDDIKULUS = 'riddikulus',
  IMMOBULUS = 'immobulus',

  PROTEGO = 'protego',
  BOMBARDA = 'bombarda',
  CONFRINGO = 'confringo',
  FERULA = 'ferula',
  VERMILLIOUS = 'vermillious',
  CISTEM_APERIO = 'cistemAperio',
  SCOURGIFY = 'scourgify',
  DIFFINDO = 'diffindo',
  ARANIA_EXUMAI = 'araniaExumai',
  COLLOPORTUS = 'colloportus',

  CHEERING_CHARM = 'cheeringCharm',
  SILENCIO = 'silencio',
  ARRESTO_MOMENTUM = 'arrestoMomentum',
  LOCOMOTOR_WIBBLY = 'locomotorWibbly',
  SALVIO_HEXIA = 'salvioHexia',
  IMPEDIMENTA = 'impedimenta',
  MIMBLEWIMBLE = 'mimblewimble',
  COUNTER_CURSE = 'counterCurse',

  REVELIO = 'revelio',
  REPARIFARGE = 'reparifarge',
  REPARO = 'reparo',
  HYSTRIFORS = 'hystrifors',
  SPONGIFY = 'spongify',

  FELIFORS = 'felifors',
  DURO = 'duro',
  STRIGIFORMA = 'strigiforma',
  MOUSE_TO_SNUFFBOX = 'mouseToSnuffbox',

  EVANESCO = 'evanesco',
  VERA_VERTO = 'veraVerto',
  BEETLE_TO_BUTTON = 'beetleToButton',
  COLOVARIA = 'colovaria',
  SERPENSORTIA = 'serpensortia',
  ORCHIDEOUS = 'orchideous',
  INCARCEROUS = 'incarcerous',
  FERRET_TO_FEATHER_DUSTER = 'ferretToFeatherDuster',
  CAULDRON_TO_GUITAR = 'cauldronToGuitar',

  AMATO_ANIMO_ANIMATO_ANIMAGUS = 'amato animo animato animagus',
  BEWITCHED_SLEEP = 'bewitched sleep',
  LEEK_JINX = 'leek jinx',
  METEOLOJINX = 'meteolojinx',
  OBLIVIATE = 'obliviate',
  OBSCURO = 'obscuro',
  SLUGULUS_ERUCTO = 'slugulus eructo',
  STUPEFIX = 'stupefix',
  WADDIWASI = 'waddiwasi'
}
